language: c

branches:
    only:
        - master
build:
    ci:
      - cd shippable
      - docker build -t zephyrprojectrtos/ci:$BRANCH.$BUILD_NUMBER .
    post_ci:
      - >
        if [ "IS_GIT_TAG" = "true" ]; then
          docker push zephyrprojectrtos/ci:$BRANCH.$BUILD_NUMBER;
        fi

integrations:
  hub:
    - integrationName: project_docker_repo
      type: docker
