language: c

branches:
    only:
        - master
build:
    ci:
      - cd shippable
      - >
        if [ "IS_GIT_TAG" = "true" ]; then
          docker build -t zephyrprojectrtos/ci:${GIT_TAG_NAME} .;
        else
          docker build -t  zephyrprojectrtos/ci:$BRANCH.$BUILD_NUMBER .;
        fi;

    post_ci:
      - >
        if [ "IS_GIT_TAG" = "true" ]; then
          docker push zephyrprojectrtos/ci:${GIT_TAG_NAME};
        fi;

integrations:
  hub:
    - integrationName: project_docker_repo
      type: docker
