language: c

branches:
    only:
        - master
build:
    ci:
      - cd shippable
      - docker build -t zephyrprojectrtos/ci:$BRANCH.$BUILD_NUMBER .
    post_ci:
      - >
        if [ "$IS_PULL_REQUEST" = "false" ]; then
          docker push zephyrprojectrtos/ci:$BRANCH.$BUILD_NUMBER;
        fi

integrations:
  hub:
    - integrationName: project_docker_repo
      type: docker
